version: '3.8'

services:
  postgres:
    image: "ankane/pgvector:v0.5.1"
    user: postgres
    environment:
      POSTGRES_USER: omnivore
      POSTGRES_PASSWORD: omnivore_change_me
      POSTGRES_DB: omnivore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omnivore -d omnivore || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  migrate:
    image: ghcr.io/omnivore-app/sh-migrate:latest
    container_name: omnivore-migrate
    command: /bin/sh ./packages/db/setup.sh
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  api:
    image: ghcr.io/omnivore-app/sh-backend:latest
    container_name: omnivore-api
    ports:
      - "4000:8080"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 0.0.0.0 8080 || exit 1"]
      interval: 15s
      timeout: 90s
      retries: 6
    env_file:
      - .env
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  queue-processor:
    image: ghcr.io/omnivore-app/sh-queue-processor:latest
    container_name: omnivore-queue-processor
    env_file:
      - .env
    depends_on:
      api:
        condition: service_started
    restart: unless-stopped

  web:
    image: ghcr.io/omnivore-app/sh-web:latest
    container_name: omnivore-web
    ports:
      - "3000:8080"
    env_file:
      - .env
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

  image-proxy:
    image: ghcr.io/omnivore-app/sh-image-proxy:latest
    container_name: omnivore-image-proxy
    ports:
      - "7070:8080"
    env_file:
      - .env
    restart: unless-stopped

  content-fetch:
    image: ghcr.io/omnivore-app/sh-content-fetch:latest
    container_name: omnivore-content-fetch
    ports:
      - "9090:8080"
    environment:
      USE_FIREFOX: "true"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7.2.4
    container_name: omnivore-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - redis_data:/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: omnivore-minio
    ports:
      - "10101:9000"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 1s
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
    command: server /data
    volumes:
      - minio_data:/data
    restart: unless-stopped

  createbuckets:
    image: minio/mc
    container_name: omnivore-createbuckets
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniominio
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      until /usr/bin/mc alias set myminio http://minio:9000 minio miniominio; do
        echo '...waiting...';
        sleep 1;
      done;
      /usr/bin/mc mb myminio/omnivore || true;
      /usr/bin/mc anonymous set public myminio/omnivore;
      exit 0;
      "
    restart: "no"

  mail-watch-server:
    image: ghcr.io/omnivore-app/sh-local-mail-watcher:latest
    container_name: omnivore-mail-watch-server
    ports:
      - "4398:8080"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  redis_data:
  minio_data:
